### ISSUE TITLE
Linux archive contains .pyc files

### ISSUE THREAD

**Issue by l0ser140** [DarkFenX/Pyfa#222]
Linux archive contains compiled config.pyc file. Its not a big problem, but I think this should not be.

**Comment by blitzmann** [comment]
I'd like this to remain open until we get something going to filter out things like this. =)

**Comment by DarkFenX** [comment]
Our instructions mention it:
https://github.com/DarkFenX/Pyfa/wiki/Updating-for-new-EVE-expansions
Section "Clean copies of resources"

**Comment by blitzmann** [comment]
Yes but he issue stems from the fact that the dist.py script now imports the config file to retrieve version info which causes the compiled file to appear. This happens after we clean the repo. The solution right now is to use `-B` flag, but i was wanting to perhaps do this in the script itself so that it isnt forgotten

**Comment by blitzmann** [comment]
This should be fixed with latest changes. Instead of importing the files, we now execute the files which store the variables we need. Executing `config.py` doesn't really have an effect besides setting variables as long as we don't add logic outside of functions in it.
