### ISSUE TITLE
Trouble Running on Linux Mint

### ISSUE THREAD

**Issue by droppedoncaprica** [DarkFenX/Pyfa#264]
So I tried downloading the Linux version of Pyfa and had an error about `sqlalchemy` not being properly installed.

Thinking I could find the package under `sqlalchemy`, I tried installing it using `sudo apt-get install sqlalchemy`, however there wasn't a package with that name.  Looking through, it seemed like there were a couple versions that were able to be installed.

First, I tried the `python3-sqlalchemy` package, however after installing and trying to run the program using `pythong pyfa.py`, it failed saying it still wasn't installed.  I think removed that package and tried installing the `pythong-sqlalchemy` package.  After installing that specific package, it got a bit further, throwing an error in the `__init__.py` file with this stack trace:

```
Traceback (most recent call last):
  File "pyfa.py", line 87, in <module>
    import service.prefetch
  File "/home/<user>/Desktop/pyfa/service/__init__.py", line 9, in <module>
    from service.update import Update
  File "/home/<user>/Desktop/pyfa/service/update.py", line 26, in <module>
    import dateutil.parser
ImportError: No module named dateutil.parser
```

I'm not super familiar with Pythong, so I don't know what specific version of `pyfa` is installed.  Any ideas?

**Comment by blitzmann** [comment]
It sounds like you're not exactly sure what to download. pyfa needs python2 (preferably 2.7), wxpython, sqlalchemy, and some other packages: https://github.com/DarkFenX/Pyfa/wiki/FAQ

python 2 and 3 are -not- interchangeable you can have both installed, but make sure you are downloading `python2-sqlalchemy` instead of `python3-sqlachemy`. Many distros have defaulted their python version to 3 so `python-sqlalchemy ` may represent the python3 package - be sure you install the correct versions.

as for running the program, make sure you invoke the correct python version. again, some distros have python 3 as the default `python` command. You may  have to run pyfa with `python2 pyfa.py`

Obviously, every distro is different and I'm not sure what the packages are called. Hope this helps.

(closing as it's not an issue with pyfa, but feel free to continue commenting if you have any other questions)

**Comment by TrentBartlem** [comment]
That's why it's best to use virtualenv so you can have different versions of python for different apps...
