### ISSUE TITLE
Deleting a fit twice crashes Pyfa

### ISSUE THREAD

**Issue by Iiridayn** [DarkFenX/Pyfa#266]
Steps to replicate:

1. Create a blank fitting.
2. Create a copy of blank fitting.
3. Double click the delete button.

The timing on this is a bit tight - much less so for larger fittings with many modules/drones/etc. I first found this by deleting a ship while renaming it (after copying) - that might make the timing easier. I have successfully replicated it with only step 1 and 3 though. (It also locked up once).

I suspect deletion doesn't have checks for if the thing to be deleted still exists - or that the checks are somehow confused if the fitting was just created.

**Comment by blitzmann** [comment]
I strongly suspect this is the same or related to #164. Unless warranted otherwise, I will close this issue for now. 

IIRC I was only able to reproduce under a specific linux distro. What platform are you experiencing this bug on? For the record, I cannot get your replication steps to work for me under Windows. =/

**Comment by Iiridayn** [comment]
Yeah, #164 seems like a good match. I'm using Arch Linux - looks like at least 3 distros are affected.
