### ISSUE TITLE
Pyfa crashes at startup with "AttributeError: 'None Type' object has no attribute 'ID'"

### ISSUE THREAD

**Issue by sylaan** [DarkFenX/Pyfa#279]
I was running the latest version before the Wx3 build, which was working fine. After upgrading to the wx3 build, Pyfa crashes at startup:

![image](https://cloud.githubusercontent.com/assets/4078999/7444810/d549a528-f195-11e4-9c25-151a48e8bafc.png)

I use Windows 7 Ultimate 64 bit.

**Comment by narthollis** [comment]
I get this same error after upgrading on windows 8.1 x64

**Comment by DarkFenX** [comment]
Can you guys remove all the data from pyfa folder (the one with the pyfa.exe) altogether and reinstalling?

The only reasonable case when it should appear is the same as with all these setlocale() bugs - installer probably doesn't properly remove all old files, and they get imported instead of files packed in library.zip. They attempt to do some custom settings on a ship which is no longer in database, generating this issue.

On a proper installations (with current installer we can say that they're proper if installed into clean dir) this issue should never happen.

**Comment by sylaan** [comment]
If I remove everything in the pyfa folder, but not the subfolders, I still get a crash after I reinstall:

![image](https://cloud.githubusercontent.com/assets/4078999/7446333/1927a72e-f1d5-11e4-8996-3f57c423f4ae.png)

If I remove everything, including subfolders, and reinstall, then it works fine.

**Comment by DarkFenX** [comment]
Thanks. It means that installer is misconfigured. I'm closing this issue, will make new one for installer.
