### ISSUE TITLE
Jackdaw light missile/rocket damage bonus

### ISSUE THREAD

**Issue by bspindler-shopzilla** [DarkFenX/Pyfa#294]
The 50% damage bonus for the jackdaw when using light missiles/rockets isn't applying.
![jackdaw](https://cloud.githubusercontent.com/assets/6119385/7948851/a059f2e4-094d-11e5-831e-259c7abf2239.png)

**Comment by blitzmann** [comment]
Yes it is. The ship bonus is not applied to the module, but instead it is applied to the charge itself. Check the list of affectors on the charge to verify.

I know that this seems like a weird way to do it, since turret damage modifications are applied to the module. But this is the way EVE handles it. The game has missiles as actual objects in the physics simulation that have a variety of defenses against (eg: firewall, defender missiles, outrunning them). Thus, the effects are applied to the charge "item" itself. Turret ammo, on the other hand, is not handled by the physics simulation as it's an instant hit. Because of this, the module gets the damage bonus and the actual hit damage is calculated based on velocity/tracking/etc of the target.

Hope this gives a bit of insight. =)
