### ISSUE TITLE
Better distribution

### ISSUE THREAD

**Issue by THUNDERGROOVE** [DarkFenX/Pyfa#295]
I suggest packaging all of the loose py/pyc/pyo/pyd except `pyfa.py` files in a zip and taking advantage of `zipimport` by adding the zip file to our `sys.path`

Pyfa could check if the file exists and if not just fallback to assuming the files exist elsewhere.  Either your current Python installation or the CWD.

If I have some time maybe I'll hack together a pull request for you.  It is a very simple change.  The system would however have to be integrated somehow in the system you use the generate releases for Github, which isn't in the repository.

**Comment by blitzmann** [comment]
Before hacking away at it, wait for Kadesh to respond. He was looking into generating new skeletons for the wx3 branch. Once that's all fixed up (unkown eta), it will be merged into the main branch and used.

btw, current distribution script (and all other scripts) are found in the `scripts/` directory

**Comment by DarkFenX** [comment]
https://github.com/DarkFenX/Pyfa/blob/wx3/setup.py

This script packs everything but dlls into single .zip directory. It works fine for windows build, however there're multiple issues with mac build which prevent the merge. Check issues with wx3 tag.

Also there were several issues with our code which broke pyfa when using such distribution model, but i believe i fixed them all.

We can even make skeletons with said .zip library - but for them to work, we will have to modify distribution scripts (so that they compile pyfa's .py files to .pycs and put them into .zip library).

I am closing this issue as it's part of wx3 branch. ETA is this autumn - while blitzmann is on his vacation and i'm busy with Alliance Tournament, it's not likely we'll have it done before that point.

**Comment by THUNDERGROOVE** [comment]
Awesome.  Glad it'll be gotten to eventually.

Have a nice vacation @blitzmann and good luck in the AT @DarkFenX
