### ISSUE TITLE
[Feature request] Set price source manually

### ISSUE THREAD

**Issue by zanglebert** [DarkFenX/Pyfa#298]
Hey

Not sure if this isn't the place for feature suggestions. If not, sorry...

My question: any chance you could allow users to set the source for ship / module prices themselves? Right now, it seems to be some aggregate, which isn't always a realistic estimate of what I have to pay. 

Usually, I will buy all parts in one place (say, Jita), so ideally I'd like to set the price source to the system I'm actually going to buy at. 

Not sure how difficult it is to get the live data required for that, or how much changes to the code this requires, but that's what I would really love to see.

**Comment by blitzmann** [comment]
This is the place for feature requests and issues alike. Thank for your input. I don't like turning down new features or user requests, but I think it's best to leave price sourcing the way it is. The effort to select region or a specific system and then writing the GUI elements is not worth it atm, considering we are focused right now on getting the wx3 build working and then work on rewriting pyfa completely later this year. Selecting a different price source will most likely be in next gen pyfa releases.

A little bit about how it works currently:

Data is collected from eve-central.com. We use The Forge market for all prices (earlier pyfa releases had the option in the source to add other regions, but only The Forge was ever added and there were no GUI elements for changing this. I remove this option to maintain simplicity in the code a few months back when rewriting the pricing service). As for the price itself, it is the 5% percentile of the sell orders.

Considering that the current set up is sourced from The Forge, the vast majority of the prices should reflect prices in Jita. We use percentile instead of avg to eliminate outliers. This is a fairly common setup for applications which gather data from eve-central, and won't be changing in the near future. It is also worth mentioning that prices in pyfa are only supposed to represent an estimate. =)
