### ISSUE TITLE
activating point or scram or web improves cap life?

### ISSUE THREAD

**Issue by jordillo** [DarkFenX/Pyfa#300]
hey! thanks for pyfa, it's an unspeakably awesome tool!

i noticed a problem where on these fits

[Dramiel, 150606 Fast Dramiel]

Navy Micro Auxiliary Power Core
Navy Micro Auxiliary Power Core
Navy Micro Auxiliary Power Core

50MN Y-T8 Compact Microwarpdrive
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]

Small Ancillary Current Router II
Small Ancillary Current Router I
Small Ancillary Current Router I

Inherent Implants 'Squire' Power Grid Management EG-603

and 

[Claw, 150606 Fast Claw]

Navy Micro Auxiliary Power Core
Navy Micro Auxiliary Power Core
Navy Micro Auxiliary Power Core
Power Diagnostic System II

50MN Y-T8 Compact Microwarpdrive
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

Small Ancillary Current Router II
Small Ancillary Current Router II

when adding a midslot module such as a point or scram or web, the value shown under "Capacitor Lasts" goes UP instead of down. 

doesn't seem quite right...

**Comment by blitzmann** [comment]
That is odd... No idea what may be causing it. I think we incorporated a fix a few weeks ago that took care of a bug in the cap code related to staggering cap, maybe this is a side effect of it.

**Comment by jordillo** [comment]
hey ryan,

thanks for the quick reply. so have you been able to replicate this error?

2015-06-06 18:54 GMT+02:00 Ryan Holmes <notifications@github.com>:

**Comment by blitzmann** [comment]
Yes I have, however I haven't really looked into it yet. =)

**Comment by OISumeko** [comment]
This is another fun capsim behaviour :smile: 

Running the fit through with capsim with the web disabled gives the values:

Time (s) | Starting cap (%) | Cap need (Gj) | Ending cap (%)
---|---|---|---
0.0 | 100.0% | 135.0 | 61.1%
10.0 | 70.8% | 135.0 | 31.9%
**20.0** | 46.7% | 135.0 | 7.9%
_30.0_ | 22.8% | 135.0 | -16.1%

And with the web enabled

Time (s) | Starting cap (%) | Cap need (Gj) | Ending cap (%)
---|---|---|---
0.0 | 100.0% | 3.0 | 99.1%
0.0 | 99.1% | 135.0 | 60.2%
5.0 | 65.5% | 3.0 | 64.6%
10.0 | 69.4% | 3.0 | 68.5%
10.0 | 68.5% | 135.0 | 29.6%
15.0 | 37.4% | 3.0 | 36.5%
20.0 | 43.9% | 3.0 | 43.1%
20.0 | 43.1% | 135.0 | 4.2%
25.0 | 10.4% | 3.0 | 9.5%
**30.0** | 16.9% | 3.0 | 16.0%
_30.0_ | 16.0% | 135.0 | -22.9%

One of the exit conditions for the simulator is if the capacitor level drops below 0, and when the simulator stops, it takes the last time value (bolded) that was recorded and shows that as the depletion time (if it isn't stable).

The problem we have here, is that it isn't strictly wrong. The cap did last until the 30 second mark, and one module did cycle correctly, but the second module failed due to insufficient cap. If we did choose to track the last-last value (or something like that) to make this output 25s in this case, it still has the issue originally noted, where having an additional module will seem to give increased cap.

What I propose, is rather than emitting the last time at which all modules were able to successfully activate (bold values), we instead track the time at which a module failed to activate due to insignificant cap (Italicized values). I think this is acceptable as in the first case, your modules are active for 29.9s, but fail to activate at the 30s mark despite your capacitor not being empty, so the 20s is a kind of pessimistic reading, and 30s would match your in-game observations a bit better. This would match up with the wall-clock times people would hear Aura say "The capacitor, is empty" in game as well (despite there still being cap). I have a solution for this ready if we want to take this approach.

How do you feel about that option @blitzmann?

**Comment by minlexx** [comment]
I agree with @OISumeko :)

**Comment by blitzmann** [comment]
I agree as well. Thanks for looking into this @OISumeko. Go ahead and make a pull request =)
