### ISSUE TITLE
Max velocity screws up after a while

### ISSUE THREAD

**Issue by resinneublem** [DarkFenX/Pyfa#326]
Hi there,

I've noticed with both the Ishtar and the Tengu the max velocity of the ship drops to 52 m/s. Even for "All 5". It also doesn't correct itself after I restart, but it will if I start a new fitting. It will just eventually corrupt.

I don't know what the problem is or how to exactly reproduce it. But I noticed it before v1.13.0. I'm using v1.13.2 right now.

**Comment by blitzmann** [comment]
Make sure there are no cloaks online. A lot of people forget to turn these off.

Also, I cannot reproduce. If you can continue playing with it and try to pinpoint the issue, thaat would be great.

You said it doesn't go away after you restart. This is good for diagnostics, as that means the issue is probably saved in the database. Send me the database file (`~/.pyfa/saveddata.db`) in an email at sable.blitzmann@gmail.com and I can take a look at it. Let me know specifically which fit is having the issue.

Screenshots can also prove useful. =)

**Comment by resinneublem** [comment]
Gah! That was exactly it. I'm sorry. Thanks.

I feel ridiculous now.
