### ISSUE TITLE
Unable to make changes to a ship projecting onto itself

### ISSUE THREAD

**Issue by Moatman** [DarkFenX/Pyfa#330]
Projection Preview issue: You can't change out modules or modify items in the cargo while a ship is projecting onto itself. You can select the "Remove Module" option in the right click menu, but it doesn't do anything. Double clicking also doesn't do it.
Drones and ammo are still added and removed properly.
Edit: Looks like the modules are removed in the calculation, but don't show as being removed. Or something like that. Atempting to change modules is doing some weird stuff (double-clicking a thermal hardener lowers kinetic resists, trying to remove a web changes resists, stuff like that). I think it's adding the previously removed module back when I attempt to remove another.

**Comment by blitzmann** [comment]
Additionally, state changes seem to work as expected as well.

Indeed, the rollback when creating the shadow fit seems to be the issue. Commenting it out allows the fit to change correctly, but also allows the shadow fit to be changed.

**Comment by blitzmann** [comment]
I rolled back database changes as I made the assumption that any operations would be commited before the recalc happened. Turns out there are a variety of functions that actually recalc the fit and then commit, such as module removal. The shadow fit operations happen during recalc, so obviously there are times when we rollback and uncommitted changes.

I can simply replace rollback with delete. 

If you want to test with these changes, please find in `eos/saveddata/fit.py` this line:

                eos.db.saveddata_session.rollback()

and replace with 

                eos.db.saveddata_session.delete(self)

**Comment by blitzmann** [comment]
Gonna close this as it seems to work well now
