### ISSUE TITLE
Cataclysmic Effect does not affect Cap transfer

### ISSUE THREAD

**Issue by Calavoow** [DarkFenX/Pyfa#354]
When applying a cataclysmic wormhole effect, incoming remote cap transfers do not get reduced by the effect.

Tried this on a dominix by applying Large Remote Capacitor Transmitter II in projected.
Related to #54 ?

**Comment by blitzmann** [comment]
Hmm... I can't remember if system effects such as this must be present on the projecting fit or the target fit for it to correctly calculate. Regardless, it does seem to be broken. I will look into it when I get some time. =)

**Comment by Calavoow** [comment]
I think we tested both, and they did not work, but please double check.

**Comment by blitzmann** [comment]
So I think I've narrowed it down, but it's not as simple as I had hoped.

When a fit is projected, it excludes it's own projections from the equation. This is so that a web that is projected onto fit `B`, which is then projected onto `A`, does not effect `A`. This is due to the assumption that projected items do not affect other projected items, and so it should be safe.

It appears we totally forgot about system effects, which do that exact thing. So what ends up happening is that when we are calculating the projecting fit, we exclude it's projected modules (of which system effects are considered), and so the effect is never run to modify it's own Cap transfer.

I don't know of a good way to fix this TBH. There are two possible solutions that come to mind:

1) Move system effect out of projected modules into it's own container.
3) Figure out a way for projected items to run their effects on the local fit when that fit is projected. This may involve checking in the effect file if the modules parent fit is modifying a different fit, or perhaps giving a different context. We might also be able to compile a list of local only items similar to the chain we already generate and check against that when running the projection logic

Unfortunately, we are somewhat limited to the current pyfa engine, which is a pain.

**Comment by blitzmann** [comment]
Turns out this wasn't too difficult to get right. Before, we would determine the items that we wanted applied depending on if the fit was projected or not. Because of this, we would not run projected effects. 

Now, we simply set up two lists: all items, and a restricted list of items which are not run on the projectee. I will be testing it more in the coming days.

Could you test as well? In the pyfa directory there is a `library.zip`. In this, under `eos/saveddata` there is `fit.py`. Could you replace that file with this version:

https://raw.githubusercontent.com/blitzmann/Pyfa/master/eos/saveddata/fit.py

I particularly interested if gang effects may be affected. I doubt it as I don't think there are any system effects that affect gang effects, but I'd like to verify. =)

**Comment by Calavoow** [comment]
I've noticed that a Large Remote Capacitor Transmitter is not affected by the system effect. So projected modules without a fit.

But it does look like the following work (in my limited testing):
* Black Hole webs
* Cataclysmic cap transfers, shield transfer and remote armor rep
* Magnetar paints
* Pulsar neuts and NOS
* Red giant heat

**Comment by blitzmann** [comment]
You mean a single Remote Cap Transmitter projected onto a fit does not have the system effects included? The system effects are only applied to fitted modules on a fit. Any explicitly projected module simply applies it's base stats and nothing more. To fix this would be a much larger change, so it's not on my radar at the moment (you would also think that projected fits would have the system effect applied even if they don't have it applied to their fit, but again, this would require a much larger reworking of the calc system)

**Comment by Calavoow** [comment]
> you would also think that projected fits would have the system effect applied even if they don't have it applied to their fit

Yes, by extension of the same point I also thought this was strange, since a projected fit cannot project anything without being suspect to the same system effect.

**Comment by blitzmann** [comment]
In a perfect world...That might be something we keep in mind with the rewrite =)

I've done some more testing with the results of these fixes, and everything looks good. Gonna close this issue.
