### ISSUE TITLE
Medium Ancillary Armor Repairer says it only holds 8 nanite repair paste

### ISSUE THREAD

**Issue by resinneublem** [DarkFenX/Pyfa#360]
Pretty much what the title says. When you add it to a cruiser and load it with paste it says "(8)" like the small version instead of the actual 32.

**Comment by blitzmann** [comment]
Hmm... that is strange.

**Comment by blitzmann** [comment]
Oh, it's because it's the number of cycles a fully loaded repairer can do. So, for a Med Ancillary Armor Repairer, it used 4 paste per cycle. 32/4 = 8 cycles.

This isn't very straightforward, but I believe the AARs are the only module that are affected? I might be able to fanangle something so that this is less confusing.

**Comment by blitzmann** [comment]
Done with e07c162453b4f7f08edbc6025fc62eef2df44dd0 =)

 ![capture](https://cloud.githubusercontent.com/assets/3904767/10120321/4197f4f4-6483-11e5-8114-2a9613e89d29.PNG)

**Comment by resinneublem** [comment]
Ahh I gotcha now. Thanks!
