### ISSUE TITLE
Medium Mercoxit Mining Crystal Optimization not factored in

### ISSUE THREAD

**Issue by Tellur86** [DarkFenX/Pyfa#376]
When fitting a "Medium Mercoxit Mining Crystal Optimatization" rig its benefit is correctly applied in the charge stats window, however the increased yield isn't applied to the yield per second calculation of the module (centre view) or the mining yield overview (right panel).

**Comment by blitzmann** [comment]
Can you please post a fit? I am not a miner and apparently I can find the correct mining laser that goes with the crystal =x

**Comment by blitzmann** [comment]
I believe I have this fixed. There were three issues: 

* `specialtyMiningAmount` attribute was not being used properly. Apparently, the ship bonus is supposed to boost the `miningAmount` attribute, but then this is copied to the `specialtyMiningAmount` attribute, too which the Mercoxit Crystal is applied to. 
* The rig's effect was being run too late, and thus not applying it's boost. This is fixed by giving it an `early` runtime.
* We were only displaying `miningAmount`, not `specialtyMiningAmount`. We now display them correctly depending on which one is available.

Just to clarify, the follow fit should give 9.61m^3/s with all 5 character, correct?

[Retriever, Retriever fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]

Modulated Deep Core Strip Miner II, Mercoxit Mining Crystal II
Modulated Deep Core Strip Miner II, Mercoxit Mining Crystal II

Medium Mercoxit Mining Crystal Optimization I
[Empty Rig slot]
[Empty Rig slot]


Mining Drone II x5

**Comment by Tellur86** [comment]
I honestly don't know what you should get out of that fit. I don't mine that much either and have never actually mined any Mercoxit (hence never used the rig). I just noticed that fitting that rig didn't change anything when it should.

Although from what I calculated by hand it should be 15.6 m³/s. Might be wrong about that though. Check my math please:

Per cycle and per Strip Miner:
Base Mining amount of Modulated Deep Core Strip Miner II: 250m³
Speciality Mining amount: 250m³
Boni applied to them both: Retriever (x1.25), Astrogeology (x1.25), Mining (x1.25)
Mining amount (Base and speciality share same value) after boni: 488.28125

Mercoxit Mining Crystal II Speciality Yield  Bonus: 1.375
Rig Bonus to this: 16% -> x1.16
Multiplier to Speciality Yield amount: x1.595

Base mining amount after all boni: 488.28125
Speciality mining amount after boni, crystal and rig: 778.80859375
Total mining amount (sum of the two): 1267.08984375

Base duration of MDCSM II: 180s
Mining Barge bonus: 0.9
Final duration: 162s

Mining yield per second: 7.821 m³/s per strip miner --> x2 for two strip miner per Retriever --> 15.64 m³/s

**Comment by Tellur86** [comment]
Here's the math as I understand it:

The Modulated Miners (Modulated Strip Miner II, Modulated Deep Core Strip Miner II, Modulated Deep Core Miner II) have a base and a speciality mining amount. They start out the same, get all the boni (skills, ship traits, modules) applied to them as usual with the only difference that the speciality mining amount also gets multiplied by the Asteroid Specialization Yield Modifier as stated in the loaded crystal's attributes. If the loaded modulated miner gets used on ore corresponding to the crystal, the Speciality Mining Amount gets used to determine yield, else the Base Mining Amount. So far those values match with what I'm getting in my old Mackinaw.
I suspect that the mercoxit rig multiplies that Asteroid Specialization Yield Modifier with 1.16. Don't really know if this suffers diminishing returns when combined with Mining Laser Upgrades though.
I can't really test this though since I don't have Mercoxit Processing yet and it would take me about 14 days to skill into it (requires Reprocessing Efficiency V :/).

**Comment by blitzmann** [comment]
sweet. I also double checked against EFT and o.smium (which apparently doesn't have a working rig either), and the result of the math is the same, so I'm going to assume it works. It's interesting to note that Mercoxit seems to be special as it's the only one with a rig to boost it with. =/

Gonna close for now

**Comment by Tellur86** [comment]
Yup, mining rigs seem to be pretty under-represented.

Glad to be of help and kudos for the good work! Keep it up!
