### ISSUE TITLE
[Win] cx_Freeze Python error in main script - locale error?

### ISSUE THREAD

**Issue by Nahaz** [DarkFenX/Pyfa#418]
I can't start Pyfa since updating to latest release (1.16.1)

I get the following error about locale:

![image](https://cloud.githubusercontent.com/assets/457154/11020188/e451a798-8617-11e5-9614-37c81840ed65.png)

The only thing I can deduct from googling is that there might be a new function to use for handling locale:
http://stackoverflow.com/questions/21444951/wxpython-3-0-breaks-older-apps-locale-error
https://groups.google.com/forum/#!topic/wx-users/9Bpn1Bwm0R0

**Comment by blitzmann** [comment]
that's strange. Were you using the wx3 v1.15 release before?

**Comment by Nahaz** [comment]
I have only upgraded pyfa from 1.15, not touched anything else

**Comment by blitzmann** [comment]
The thing is that we don't set the locale. There was a time once when we did, but the command has been removed since.

Did you simply extract the new version tot he old installation directory? If you were using the non-wx3 version of the Windows build, then you're going to have the new directory structure on top of the old one, which is going to cause all sorts of problems. There were warning about this in previous release notes while the wx3 testing was taking place - admittedly I probably should have made a note with this new release as well.

Please delete the pyfa directory and try to extract it fresh, and let me know how it goes =)

**Comment by Nahaz** [comment]
That seems to have fixed it :)

**Comment by blitzmann** [comment]
Nice. I am making a new release right now with some fixes, and I'll be sure to add a note about this.
