### ISSUE TITLE
Cov Ops Cloak not being correctly modified with skills

### ISSUE THREAD

**Issue by JoshuaNotowitz** [DarkFenX/Pyfa#434]
it appears the the all 5 character is not applying its cov ops lvl to the cov ops frigate
<img width="1249" alt="screen shot 2015-11-16 at 7 30 00 am" src="https://cloud.githubusercontent.com/assets/8390690/11186151/32d038ee-8c35-11e5-88d6-7fdf5e558e03.png">
<img width="1249" alt="screen shot 2015-11-16 at 7 29 48 am" src="https://cloud.githubusercontent.com/assets/8390690/11186152/32e3fbb8-8c35-11e5-843c-a8ce7fb05ad7.png">
Not sure if this happens with any other ships

**Comment by thorr18** [comment]
This is an issue only with 1.16.1; should download 1.16.2 and try again. 
Dupe #406

**Comment by blitzmann** [comment]
There were a lot of what looks like duplicates to #406, so I went back to check things.

Actually... it seems there is some kind of bug. Creating a new Anathema fit and adding the Cov Ops cloak shows 100 CPU usage. But when recalculating the fit (changing character, adding a module, changing module state, etc) the proper CPU usage (0) is used. So there's some sort of disconnect here.

**Comment by blitzmann** [comment]
I've narrowed it down to the `__handleSkill()` function in `modifiedAttributeDict.py`

```
def __handleSkill(self, skillName):
        """
        Since ship skill bonuses do not directly modify the attributes, it does
        not register as an affector (instead, the ship itself is the affector).
        To fix this, we pass the skill which ends up here, where we register it
        with the fit and thus get the correct affector. Returns skill level to
        be used to modify modifier. See GH issue #101
        """
        skill = self.fit.character.getSkill(skillName)
        self.fit.register(skill)
        return skill.level
```

Seems that `self.fit` is `None` when this effect is run. I will continue to investigate, but I wonder how many other calculations are affected by this.

**Comment by blitzmann** [comment]
So here's what's happening:

When we run calculations, we pass an iterable which includes in this order: `character`, `ship`, `drones`, `boosters`, `implants`, `modules`. While looping through these, the fit that is the parent is attached to the modified attribute dictionary. The problem here is that the ship is processed before the modules. This means that the ship effects (which the cloak reduction is a part of) is run before the module has the fit stored in it's variable.

This doesn't affect most effects, as most effects are in the normal runtime when all of the items have been assigned a fit. 

The reason it doesn't (seem to) happen when a fit is first loaded is simply because due to :reasons: pyfa actually calculated the fit twice when loading from the database. So it actually doesn't work the first time, but works the second time.

Not sure what a good fix to this would be, we'll see
