### ISSUE TITLE
Text appearance of wx3 on retina displays

### ISSUE THREAD

**Issue by UberMitchROCKS** [DarkFenX/Pyfa#435]
Just installed wx3 on my mid-2015 Macbook Pro. The text with the fitting, the stats, etc., looks *great* on the retina display, but in the text in list of saved fits, the tab titles, and the resistance percentages is all sorts of fuzzy (pic below). I don't believe it appeared this way on the previous build. LITERALLY UNPLAYABLE :)
Anyway, thanks for making such a great service!
<img width="1406" alt="screen shot 2015-11-16 at 8 40 59 pm" src="https://cloud.githubusercontent.com/assets/15883145/11202968/3617689c-8ca3-11e5-8dd4-c78ee9f36afd.png">

**Comment by thorr18** [comment]
I think we mentioned this in #398 too

**Comment by blitzmann** [comment]
Yeah, the text has always been fuzzy apparently. the wx3 build actually improved on it. If I understand it correctly, it's because those things are actually bitmap images and not actually text (as rendered by the operating system). You can see all other images are fuzzy.

Unfortunately, not much progress can be made on this as I don't have an actual Mac or Retina Display, just a Hackintosh. I don't know how to increase the DPI on these images. Please subscribe to #398 and #289 - if I make any progress, I will be asking for testing in those threads. Closing.
