### ISSUE TITLE
Default store rat damage patterns

### ISSUE THREAD

**Issue by ChrisKing517** [DarkFenX/Pyfa#444]
You should add in the default ratting damage patterns to be stored in pyfa already without having to add them.  Not sure why not...they never change

http://wiki.eveuniversity.org/NPC_Damage_Types

**Comment by blitzmann** [comment]
This would require seeding the database with this information when we create it, which is kind of a pain to do. Then we need to consider how to modify this if it ever changes (it has changed before IIRC) or if rats are added (like drifters, or the burner mission rats). Damage profiles are part of the user database, and I try not to touch that if I can avoid it as it should only ever contain user-supplied information.

The biggest reason not to do it is simply because there are no official numbers in place for these types of things. The damage profiles are largely a community-collected set of profiles (rat damage information used to be part of the CCP database, but I believe it's been removed for many years now).

pyfa uses the same format as EFT, and has some default values on the wiki (https://github.com/DarkFenX/Pyfa/wiki/Effective-HP), making it easy for folks to import if they wish to do so.

**Comment by ChrisKing517** [comment]
That link is exactly what I was really asking for.  Didn't know it existed....you could add a link to that or something on the damage profile page.  Thanks though

**Comment by blitzmann** [comment]
Yeah, it would probably be a good idea to add a button that takes you to the wiki page. Will keep that in mind next time I'm fiddling with the GUI =)
