### ISSUE TITLE
SSL Cert verify fails on OSX 10.10.5 (Yosemite)

### ISSUE THREAD

**Issue by cpmcdaniel** [DarkFenX/Pyfa#457]
When trying to fetch my character sheet through the Character Editor API tab, I get the following error:
SSL: CERTIFICATE_VERIFY_FAILED

I tried a bit of googling as I am an experienced Python developer (but not so experienced with SSL). I tried updating openssl through brew. I even going to the eve API in my web browser, exporting the cert, and putting it in openssl's trusted certs directory. Still no luck. If there is any further tricks I can try (or information I can add) to help us solve this issue, let me know.

**Comment by blitzmann** [comment]
Duplicate #432. This issue has been fixed internally. It will be available with the December release.

The problem was 2 things: 
* the Python binaries were updated to 2.7.10, which now verify SSL connections by default
* The certs could not be verified due to problems finding the cert path. It was fixed by overriding the path to a relative directory to look at a cert that ships with pyfa.

As for a fix for it right now, the best I can do is tell you to use the basic `-mac` build until the December release. You could use that to update the character skills and then use the `-mac-wx3` build as normal.
