### ISSUE TITLE
Starting pyfa fails.

### ISSUE THREAD

**Issue by rescuetoaster** [DarkFenX/Pyfa#465]
System: Debian 7.8
Python: 2.6.8

Fails with following:
```
martini@juustukeII:~/Documents/Games/Pyfa/pyfa$ ./pyfa.py 
Traceback (most recent call last):
  File "./pyfa.py", line 116, in <module>
    import service.prefetch
  File "/home/martini/Documents/Games/Pyfa/pyfa/service/__init__.py", line 16, in <module>
    from service.pycrest import EVE
  File "/home/martini/Documents/Games/Pyfa/pyfa/service/pycrest/__init__.py", line 13, in <module>
    from .eve import EVE
  File "/home/martini/Documents/Games/Pyfa/pyfa/service/pycrest/eve.py", line 11, in <module>
    from requests.adapters import HTTPAdapter
ImportError: No module named adapters
martini@juustukeII:~/Documents/Games/Pyfa/pyfa$ 
```
Installed 3.0.4 but thats too high apparently?

Tried master download without success.

**Comment by blitzmann** [comment]
Did the 1.16.2 version work for you?

It seems like yiu may not have the requests python module. Make sure that is installed

**Comment by rescuetoaster** [comment]
Hi!
1.16.2 had same issue.
python-requests package is installed (0.12.1-1+deb7u1) for amd64 architecture.

**Comment by blitzmann** [comment]
You say that you "Installed 3.0.4", what did you mean by this? 

I would make sure all your python packages are up to date. I will look into that import error this week and hopefully find an answer.

**Comment by rescuetoaster** [comment]
I also built 3.0.4 beside the 2.6 to check will newer python solve the problem. It seems pyfa only accepts 3.0 max

**Comment by rescuetoaster** [comment]
1.15 pyfa worked fine on my setup and i can fire it up again if i want to its just outdated.

**Comment by blitzmann** [comment]
Which version of the requests package do you have? 

```
import requests
requests.__version__
```

**Comment by rescuetoaster** [comment]
requests is  0.12.1
how do I check wxpython version please?

**Comment by blitzmann** [comment]
I beleive you need requests to at least be 1.0. Please update.

Wx version should be fine as it checks that when first starts

**Comment by blitzmann** [comment]
Your version of requests is over 3 years old. >_>

**Comment by rescuetoaster** [comment]
Surfed around and managed to get requests 2.8.1 for python3
when trying to run pyfa.py I now get:
martini@juustukeII:~/Documents/Games/Pyfa/17/pyfa$ python3 ./pyfa.py 
  File "./pyfa.py", line 37
    except (BadOptionError,AmbiguousOptionError), e:
                                                ^
SyntaxError: invalid syntax

**Comment by blitzmann** [comment]
Python 2.6 requires that `stirng.format()` be fed positional argument, however there is many places in the code that omits these and uses, for example, `"{}".format(var)` instead of `"{0}".format(var)`. Install and use python 2.7 instead of 2.6. 

I understand that the README says that 2.6 is the minimum, but this is a case of the minimum requirements not keeping up with development. I will work on getting more accurate information on the README, and this issue is proving very helpful in determining what needs to be updated. =)

**Comment by blitzmann** [comment]
Try to get the latest version of python 2.7, and then download the other packages via `pip install` to ensure the latest version.

**Comment by thorr18** [comment]
I had good luck with [playdeb](http://www.playdeb.net/game/Python%20Fitting%20Assistant) After I asked them to add Requests to it a couple months ago, it took care of dependancies reliably. 
Perhaps such conveniences aren't an option on your distro, I wouldn't know, but I thought I'd mention it.

**Comment by blitzmann** [comment]
@rescuetoaster, can you please report if you were able to get things working again?

I'm going to mark this as fixed as it seems to me is simply a problem with module versions and whatnot, and assume you have it working. This will be closed when we release the next version. Let me know if you're still having difficulty.

**Comment by jsaak** [comment]
i do not know why you marked it as fixed, i still have this problem (using requests version 0.12.1)

what i needed to do was this:

```
sudo apt-get install python-pip
sudo pip install --upgrade requests
```

**Comment by blitzmann** [comment]
@jsaak are you @rescuetoaster?  

I marked as fixed and closed the issue because 1) @rescuetoaster stopped responding, and 2) this isn't really a pyfa issue, but rather a local issue related to the packages on your system and their versions (as stated above, requests 0.12.1 is very old, and Python 2.7 is now the minimum version required for pyfa as per the updated README).

**Comment by jsaak** [comment]
I am a different person.
I know that you can not update all python installations on every machine. But you can include instructions for non programming people how to update them. (i am on debian wheezy, and it has python 2.7.3, and requests 0.12.1) So python 2.7 requirements is sadly not enough.

Also i needed
```
sudo apt-get install python-wxgtk2.8 python-sqlalchemy
```

**Comment by blitzmann** [comment]
I understand that there are instances where upgrades are not possible (due to organization security restrictions or the like, similar to how there are still Windows XP systems in place). However, I'm of the opinion that if you are running Linux, you generally know what you are working with and can either update through the distro repos or use something similar to `pip` to upgrade packages (you can usually use `pip` to install or upgrade any python module). If you are in a situation in which you do not have administrative access to do these things (such as at work), then that's on the user to get the access required. 

I don't know your specific situation so I won't comment, and I'm glad you got it up and running. Unfortunately it's difficult to provide linux instructions considering all the different repos out there. All I can say is that once Python 2.7 and wxPython 2.8 / 3.0 is installed via the distro repositories, you can then use `pip` to install the other required modules. But again, this isn't a pyfa issue, rather it's an issue of a out of date system.

Also, there is someone who compiles the pyfa release into .deb files which might make it easier to install. I don't offer any support with it however https://github.com/AdamMajer/Pyfa/releases

Best =)
