### ISSUE TITLE
Civilian weapons not available.

### ISSUE THREAD

**Issue by bugme143** [DarkFenX/Pyfa#477]
If you're attempting to import a fit from clipboard that has civilian weapons, the fit will refuse to import.

**Comment by blitzmann** [comment]
This could simply be related to #474 and no civilian weapons. They are available on the market and can be added to fits. Will keep this open until I figure out more.

**Comment by blitzmann** [comment]
Can you post the fit here that you are having trouble with

**Comment by bugme143** [comment]
[Eos, Eos]

Centum B-Type Medium Armor Repairer
Reactive Armor Hardener
Drone Damage Amplifier II
Drone Damage Amplifier II
Drone Damage Amplifier II
Corelum B-Type Medium Armor Repairer

Drone Navigation Computer II
Federation Navy 10MN Afterburner
Federation Navy Omnidirectional Tracking Link
Cap Recharger II

Drone Link Augmentor II
Drone Link Augmentor II
Armored Warfare Link - Rapid Repair I
Civilian Light Electron Blaster
Armored Warfare Link - Passive Defense I
Armored Warfare Link - Damage Control I

Medium Capacitor Control Circuit II
Medium Capacitor Control Circuit II


Wasp II x5
Ogre II x5


Optimal Range Script x5
Tracking Speed Script x4

**Comment by blitzmann** [comment]
k, well this is due to `Civilian Light Electron Blaster` not existing in the database / game, but it was complicated due to the bug in #474. That bug has been fixed for the next release, so this fit should import fine afterwards.

**Comment by bugme143** [comment]
Huh, that's (#474) rather interesting. Is there a way to add *all* the civ modules without them being in the CCP market database? I know that we use civ guns all the time for our drone fits.

**Comment by blitzmann** [comment]
Civilian weapons are a special snowflake in that there is no way to obtain them but to get them through the rookie ships (not even sure if it's available in contracts - at least I can't find them). It is true that we don't add them to our database, as we filter what goes in based on the published value. Hut, I tweaked a few things so that civilian weapons are added.

![dsdsdsdsdsd](https://cloud.githubusercontent.com/assets/3904767/11921809/ed0e9d80-a75c-11e5-8725-f09eb572a41d.PNG)

Will be out with next release. =)

**Comment by bugme143** [comment]
<3 You are awesome!
