### ISSUE TITLE
Logi frigate skill doesn't affect cap usage on RSB

### ISSUE THREAD

**Issue by Mncdk** [DarkFenX/Pyfa#488]
I've tried messing about with the Kirin and the Scalpel, and I've noticed that as I adjust between Logistics Frigate level 4 and 5, the cap usage on the remote shield boosters does not change.

I only have racial frigate trained to 5 for one of them, so I have made sure the bug exists for both ships.

I couldn't find an existing issue for this, I searched the existing issues for 'logi' in their title.

**Comment by blitzmann** [comment]
I see what you are saying: the cap usage column on the fitting window does not update, nor do the stats on the right. However, looking at the item info and affected by tab, it is showing as applying correctly.

I'll have a look into this discrepancy. Thanks!

**Comment by blitzmann** [comment]
k, looked into it, and it seems it it working as expected. The Logistics Frigate skill modifies both the cap usage and the amount by the same percentage. his is the reason why you do not see the cap stats change, because they effectively don't. This allows the repper to rep more per second without changing the cap usage

Example: 
* With all V except Logi Frigate at lvl 1, the cap usage is 20.7 GJ per 3.8 seconds, which is 5.44/s 
* With all V including Logi Frigate, the cap usage is 16.3 GJ per 3 seconds, which is 5.43/s (but with other various rounding in other calculations, shows as 5.44/s) 

Gonna close this. =)
