### ISSUE TITLE
Projected Fit infinite recursion

### ISSUE THREAD

**Issue by dachucky** [DarkFenX/Pyfa#72]
If you project fit A onto fit B, then project fit B onto fit A, this will cause the fits to be recursively projected onto each other infinitely eventually hitting Python's recursion limit. This will break both fits until one is deleted, as well as any fit that either fit is projected onto.

Best way to try this is to create two new blank fittings and project each one onto the other.

**Comment by blitzmann** [comment]
I'm going to make another serious effort on this in addition to #83 

The main points to keep in mind are that there should only be 1 degree of projection. If we have `A > B > C`, we should only calculate `B` along with it's ganglinks and apply them to `A`. `C does not need to be calculated, although it currently is. I believe this will also make it possible to project a fit onto itself, but that is not a priority.

I think the previous fix might help out. I think the reason it gave weird stats was because we did not limit the recursion to 1 degree and thus it kept applying attributes to weird locations. Again, will have to look more into this.

**Comment by blitzmann** [comment]
Should be fixed with the merge e74e2615ad45f00a200477e880e61b67e6f153eb
